import { setupWorker } from 'msw/browser';

import { handlers } from './handlers';

/**
 * MSW browser worker. Imported lazily from `main.tsx` only when
 * `VITE_USE_MOCK=true`, so production builds never bundle MSW code.
 *
 * The service worker file at `/mockServiceWorker.js` is auto-generated by
 * MSW's postinstall hook (see `msw.workerDirectory` in `package.json`).
 */
export const worker = setupWorker(...handlers);
